front:
  build: .
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysql:mysql

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql
  ports:
    - 8183:80
  environment:
    MYSQL_USERNAME: admin
    MYSQL_ROOT_PASSWORD: admin
    PMA_ARBITRARY: 1

mongodata:
  image: mongo:latest
  volumes:
    - /data/db
  command: --break-mongo
# use script for users create 
# dcrun mongo mongo --host DOCKER_HOST_IP < ~/path/to/mongo-user-script.js

mongo:  
  image: mongo:latest
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest --auth
# -> remember disable --auth first run time script
